### ISSUE TITLE
QueueClient.Send never returns, and never sends message

### ISSUE THREAD

**Issue by lostmsu** [ppatierno/azuresblite#1]
Here's what I do:

``` csharp
var queue = QueueClient.CreateFromConnectionString(connectionString, QueueName);
using(var bodyStream = new MemoryStream())
{
    this.taskSerializer.WriteObject(bodyStream, contentObject);
    bodyStream.Flush();
    bodyStream.Position = 0;
    BrokeredMessage message = new BrokeredMessage(bodyStream);
    message.ContentType = "application/json";
    message.Properties["time"] = DateTime.UtcNow;
    tasksQueue.Send(message);
}
```

The last Send never returns, and nothing is sent to the queue.

**Comment by lostmsu** [comment]
I just checked in simple console app, and issue does not seem to repro. It reproes, however, in ASP.NET app. Let me build a minimal repro.

**Comment by lostmsu** [comment]
Basically, it hangs, when it runs in async Controller method. I wrapped it into Task.Run, and it passes successfully now. Will provide a repro sometime later.

**Comment by ppatierno** [comment]
It's a normal behavior due to underlying implementation of AMQP .Net Lite library.
